-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity euc_dist_sqrt_fixed_31_31_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (29 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of euc_dist_sqrt_fixed_31_31_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_4000 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal x_read_reg_1270 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln258_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_reg_1275 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln263_fu_208_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln263_reg_1282 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_l_I_3_fu_303_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_3_reg_1287 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_1_fu_311_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_1_reg_1293 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_2_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_2_reg_1299 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_1_fu_353_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln263_1_reg_1305 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_l_I_7_fu_448_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_7_reg_1310 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_5_fu_456_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_5_reg_1316 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_4_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_4_reg_1322 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_3_fu_498_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln263_3_reg_1328 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_l_I_11_fu_593_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_11_reg_1333 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_9_fu_601_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_9_reg_1339 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_6_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_6_reg_1345 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_5_fu_643_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln263_5_reg_1351 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_l_I_15_fu_738_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_15_reg_1356 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_13_fu_746_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_13_reg_1362 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_8_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_8_reg_1368 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_7_fu_788_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln263_7_reg_1374 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_l_I_19_fu_883_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_19_reg_1379 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_17_fu_891_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_17_reg_1385 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_10_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_10_reg_1391 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_9_fu_933_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln263_9_reg_1397 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_l_I_23_fu_1028_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_23_reg_1402 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_21_fu_1036_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_21_reg_1408 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_12_fu_1072_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_12_reg_1414 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_11_fu_1078_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln263_11_reg_1420 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_l_I_27_fu_1173_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal x_l_I_27_reg_1425 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_25_fu_1181_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_25_reg_1431 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_14_fu_1205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln258_14_reg_1437 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln263_13_fu_1211_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln263_13_reg_1443 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_188_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln258_fu_198_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln212_fu_214_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln263_fu_217_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_l_I_fu_220_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln216_1_fu_244_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal x_l_I_1_fu_230_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_3_fu_251_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_259_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln258_1_fu_267_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln263_fu_277_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln216_fu_237_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln258_1_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_2_fu_283_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_fu_293_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_319_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_327_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_fu_335_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln258_2_fu_343_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_l_I_4_fu_359_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_2_fu_367_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_3_fu_382_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_388_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_l_I_5_fu_376_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_7_fu_396_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_9_fu_404_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln258_3_fu_412_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln263_2_fu_422_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln258_3_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_6_fu_428_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_4_fu_438_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_464_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_472_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_10_fu_480_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln258_4_fu_488_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_l_I_8_fu_504_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_6_fu_512_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_7_fu_527_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_533_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal x_l_I_9_fu_521_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_12_fu_541_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_549_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln258_5_fu_557_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln263_4_fu_567_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln258_5_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_10_fu_573_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_8_fu_583_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_14_fu_609_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_617_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_16_fu_625_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln258_6_fu_633_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_l_I_12_fu_649_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_10_fu_657_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_11_fu_672_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_fu_678_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_l_I_13_fu_666_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_18_fu_686_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_19_fu_694_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln258_7_fu_702_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln263_6_fu_712_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln258_7_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_14_fu_718_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_12_fu_728_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_20_fu_754_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_21_fu_762_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_22_fu_770_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln258_8_fu_778_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_l_I_16_fu_794_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_14_fu_802_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_15_fu_817_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_23_fu_823_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_l_I_17_fu_811_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_24_fu_831_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_25_fu_839_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln258_9_fu_847_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln263_8_fu_857_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln258_9_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_18_fu_863_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_16_fu_873_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_26_fu_899_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_27_fu_907_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_28_fu_915_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln258_10_fu_923_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_l_I_20_fu_939_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_18_fu_947_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_19_fu_962_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_29_fu_968_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_l_I_21_fu_956_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_30_fu_976_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_31_fu_984_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln258_11_fu_992_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln263_10_fu_1002_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln258_11_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_22_fu_1008_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_20_fu_1018_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_32_fu_1044_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_33_fu_1052_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_34_fu_1060_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln258_12_fu_1068_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_l_I_24_fu_1084_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_22_fu_1092_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_23_fu_1107_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_35_fu_1113_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_l_I_25_fu_1101_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_36_fu_1121_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_37_fu_1129_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln258_13_fu_1137_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln263_12_fu_1147_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln258_13_fu_1141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_l_I_26_fu_1153_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_24_fu_1163_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_38_fu_1189_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln258_fu_1197_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln258_14_fu_1201_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal x_l_I_28_fu_1217_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal res_I_26_fu_1225_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_27_fu_1240_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_l_I_29_fu_1234_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln295_fu_1246_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln295_fu_1250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln340_fu_1256_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_int_reg : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    x_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            x_int_reg <= x;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln263_reg_1282 <= add_ln263_fu_208_p2;
                icmp_ln258_10_reg_1391 <= icmp_ln258_10_fu_927_p2;
                icmp_ln258_12_reg_1414 <= icmp_ln258_12_fu_1072_p2;
                icmp_ln258_14_reg_1437 <= icmp_ln258_14_fu_1205_p2;
                icmp_ln258_2_reg_1299 <= icmp_ln258_2_fu_347_p2;
                icmp_ln258_4_reg_1322 <= icmp_ln258_4_fu_492_p2;
                icmp_ln258_6_reg_1345 <= icmp_ln258_6_fu_637_p2;
                icmp_ln258_8_reg_1368 <= icmp_ln258_8_fu_782_p2;
                icmp_ln258_reg_1275 <= icmp_ln258_fu_202_p2;
                res_I_13_reg_1362 <= res_I_13_fu_746_p3;
                res_I_17_reg_1385 <= res_I_17_fu_891_p3;
                res_I_1_reg_1293 <= res_I_1_fu_311_p3;
                res_I_21_reg_1408 <= res_I_21_fu_1036_p3;
                res_I_25_reg_1431 <= res_I_25_fu_1181_p3;
                res_I_5_reg_1316 <= res_I_5_fu_456_p3;
                res_I_9_reg_1339 <= res_I_9_fu_601_p3;
                sub_ln263_11_reg_1420 <= sub_ln263_11_fu_1078_p2;
                sub_ln263_13_reg_1443 <= sub_ln263_13_fu_1211_p2;
                sub_ln263_1_reg_1305 <= sub_ln263_1_fu_353_p2;
                sub_ln263_3_reg_1328 <= sub_ln263_3_fu_498_p2;
                sub_ln263_5_reg_1351 <= sub_ln263_5_fu_643_p2;
                sub_ln263_7_reg_1374 <= sub_ln263_7_fu_788_p2;
                sub_ln263_9_reg_1397 <= sub_ln263_9_fu_933_p2;
                x_l_I_11_reg_1333 <= x_l_I_11_fu_593_p3;
                x_l_I_15_reg_1356 <= x_l_I_15_fu_738_p3;
                x_l_I_19_reg_1379 <= x_l_I_19_fu_883_p3;
                x_l_I_23_reg_1402 <= x_l_I_23_fu_1028_p3;
                x_l_I_27_reg_1425 <= x_l_I_27_fu_1173_p3;
                x_l_I_3_reg_1287 <= x_l_I_3_fu_303_p3;
                x_l_I_7_reg_1310 <= x_l_I_7_fu_448_p3;
                x_read_reg_1270 <= x_int_reg;
            end if;
        end if;
    end process;
    add_ln263_fu_208_p2 <= std_logic_vector(unsigned(zext_ln258_fu_198_p1) + unsigned(ap_const_lv3_7));
    add_ln340_fu_1256_p2 <= std_logic_vector(unsigned(res_I_27_fu_1240_p3) + unsigned(ap_const_lv16_1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        add_ln340_fu_1256_p2 when (icmp_ln295_fu_1250_p2(0) = '1') else 
        res_I_27_fu_1240_p3;
    icmp_ln258_10_fu_927_p2 <= "1" when (unsigned(tmp_28_fu_915_p3) < unsigned(zext_ln258_10_fu_923_p1)) else "0";
    icmp_ln258_11_fu_996_p2 <= "1" when (unsigned(tmp_31_fu_984_p3) < unsigned(zext_ln258_11_fu_992_p1)) else "0";
    icmp_ln258_12_fu_1072_p2 <= "1" when (unsigned(tmp_34_fu_1060_p3) < unsigned(zext_ln258_12_fu_1068_p1)) else "0";
    icmp_ln258_13_fu_1141_p2 <= "1" when (unsigned(tmp_37_fu_1129_p3) < unsigned(zext_ln258_13_fu_1137_p1)) else "0";
    icmp_ln258_14_fu_1205_p2 <= "1" when (unsigned(trunc_ln258_fu_1197_p1) < unsigned(zext_ln258_14_fu_1201_p1)) else "0";
    icmp_ln258_1_fu_271_p2 <= "1" when (unsigned(tmp_2_fu_259_p3) < unsigned(zext_ln258_1_fu_267_p1)) else "0";
    icmp_ln258_2_fu_347_p2 <= "1" when (unsigned(tmp_8_fu_335_p3) < unsigned(zext_ln258_2_fu_343_p1)) else "0";
    icmp_ln258_3_fu_416_p2 <= "1" when (unsigned(tmp_9_fu_404_p3) < unsigned(zext_ln258_3_fu_412_p1)) else "0";
    icmp_ln258_4_fu_492_p2 <= "1" when (unsigned(tmp_10_fu_480_p3) < unsigned(zext_ln258_4_fu_488_p1)) else "0";
    icmp_ln258_5_fu_561_p2 <= "1" when (unsigned(tmp_13_fu_549_p3) < unsigned(zext_ln258_5_fu_557_p1)) else "0";
    icmp_ln258_6_fu_637_p2 <= "1" when (unsigned(tmp_16_fu_625_p3) < unsigned(zext_ln258_6_fu_633_p1)) else "0";
    icmp_ln258_7_fu_706_p2 <= "1" when (unsigned(tmp_19_fu_694_p3) < unsigned(zext_ln258_7_fu_702_p1)) else "0";
    icmp_ln258_8_fu_782_p2 <= "1" when (unsigned(tmp_22_fu_770_p3) < unsigned(zext_ln258_8_fu_778_p1)) else "0";
    icmp_ln258_9_fu_851_p2 <= "1" when (unsigned(tmp_25_fu_839_p3) < unsigned(zext_ln258_9_fu_847_p1)) else "0";
    icmp_ln258_fu_202_p2 <= "1" when (tmp_fu_188_p4 = ap_const_lv2_0) else "0";
    icmp_ln295_fu_1250_p2 <= "1" when (unsigned(x_l_I_29_fu_1234_p3) > unsigned(zext_ln295_fu_1246_p1)) else "0";
    
    res_I_10_fu_657_p4_proc : process(res_I_9_reg_1339)
    begin
        res_I_10_fu_657_p4 <= res_I_9_reg_1339;
        res_I_10_fu_657_p4(8) <= ap_const_lv1_1(0);
    end process;

    res_I_11_fu_672_p3 <= 
        res_I_9_reg_1339 when (icmp_ln258_6_reg_1345(0) = '1') else 
        res_I_10_fu_657_p4;
    
    res_I_12_fu_728_p4_proc : process(res_I_11_fu_672_p3)
    begin
        res_I_12_fu_728_p4 <= res_I_11_fu_672_p3;
        res_I_12_fu_728_p4(7) <= ap_const_lv1_1(0);
    end process;

    res_I_13_fu_746_p3 <= 
        res_I_11_fu_672_p3 when (icmp_ln258_7_fu_706_p2(0) = '1') else 
        res_I_12_fu_728_p4;
    
    res_I_14_fu_802_p4_proc : process(res_I_13_reg_1362)
    begin
        res_I_14_fu_802_p4 <= res_I_13_reg_1362;
        res_I_14_fu_802_p4(6) <= ap_const_lv1_1(0);
    end process;

    res_I_15_fu_817_p3 <= 
        res_I_13_reg_1362 when (icmp_ln258_8_reg_1368(0) = '1') else 
        res_I_14_fu_802_p4;
    
    res_I_16_fu_873_p4_proc : process(res_I_15_fu_817_p3)
    begin
        res_I_16_fu_873_p4 <= res_I_15_fu_817_p3;
        res_I_16_fu_873_p4(5) <= ap_const_lv1_1(0);
    end process;

    res_I_17_fu_891_p3 <= 
        res_I_15_fu_817_p3 when (icmp_ln258_9_fu_851_p2(0) = '1') else 
        res_I_16_fu_873_p4;
    
    res_I_18_fu_947_p4_proc : process(res_I_17_reg_1385)
    begin
        res_I_18_fu_947_p4 <= res_I_17_reg_1385;
        res_I_18_fu_947_p4(4) <= ap_const_lv1_1(0);
    end process;

    res_I_19_fu_962_p3 <= 
        res_I_17_reg_1385 when (icmp_ln258_10_reg_1391(0) = '1') else 
        res_I_18_fu_947_p4;
    res_I_1_fu_311_p3 <= 
        select_ln216_fu_237_p3 when (icmp_ln258_1_fu_271_p2(0) = '1') else 
        res_I_fu_293_p4;
    
    res_I_20_fu_1018_p4_proc : process(res_I_19_fu_962_p3)
    begin
        res_I_20_fu_1018_p4 <= res_I_19_fu_962_p3;
        res_I_20_fu_1018_p4(3) <= ap_const_lv1_1(0);
    end process;

    res_I_21_fu_1036_p3 <= 
        res_I_19_fu_962_p3 when (icmp_ln258_11_fu_996_p2(0) = '1') else 
        res_I_20_fu_1018_p4;
    
    res_I_22_fu_1092_p4_proc : process(res_I_21_reg_1408)
    begin
        res_I_22_fu_1092_p4 <= res_I_21_reg_1408;
        res_I_22_fu_1092_p4(2) <= ap_const_lv1_1(0);
    end process;

    res_I_23_fu_1107_p3 <= 
        res_I_21_reg_1408 when (icmp_ln258_12_reg_1414(0) = '1') else 
        res_I_22_fu_1092_p4;
    
    res_I_24_fu_1163_p4_proc : process(res_I_23_fu_1107_p3)
    begin
        res_I_24_fu_1163_p4 <= res_I_23_fu_1107_p3;
        res_I_24_fu_1163_p4(1) <= ap_const_lv1_1(0);
    end process;

    res_I_25_fu_1181_p3 <= 
        res_I_23_fu_1107_p3 when (icmp_ln258_13_fu_1141_p2(0) = '1') else 
        res_I_24_fu_1163_p4;
    
    res_I_26_fu_1225_p4_proc : process(res_I_25_reg_1431)
    begin
        res_I_26_fu_1225_p4 <= res_I_25_reg_1431;
        res_I_26_fu_1225_p4(0) <= ap_const_lv1_1(0);
    end process;

    res_I_27_fu_1240_p3 <= 
        res_I_25_reg_1431 when (icmp_ln258_14_reg_1437(0) = '1') else 
        res_I_26_fu_1225_p4;
    
    res_I_2_fu_367_p4_proc : process(res_I_1_reg_1293)
    begin
        res_I_2_fu_367_p4 <= res_I_1_reg_1293;
        res_I_2_fu_367_p4(12) <= ap_const_lv1_1(0);
    end process;

    res_I_3_fu_382_p3 <= 
        res_I_1_reg_1293 when (icmp_ln258_2_reg_1299(0) = '1') else 
        res_I_2_fu_367_p4;
    
    res_I_4_fu_438_p4_proc : process(res_I_3_fu_382_p3)
    begin
        res_I_4_fu_438_p4 <= res_I_3_fu_382_p3;
        res_I_4_fu_438_p4(11) <= ap_const_lv1_1(0);
    end process;

    res_I_5_fu_456_p3 <= 
        res_I_3_fu_382_p3 when (icmp_ln258_3_fu_416_p2(0) = '1') else 
        res_I_4_fu_438_p4;
    
    res_I_6_fu_512_p4_proc : process(res_I_5_reg_1316)
    begin
        res_I_6_fu_512_p4 <= res_I_5_reg_1316;
        res_I_6_fu_512_p4(10) <= ap_const_lv1_1(0);
    end process;

    res_I_7_fu_527_p3 <= 
        res_I_5_reg_1316 when (icmp_ln258_4_reg_1322(0) = '1') else 
        res_I_6_fu_512_p4;
    
    res_I_8_fu_583_p4_proc : process(res_I_7_fu_527_p3)
    begin
        res_I_8_fu_583_p4 <= res_I_7_fu_527_p3;
        res_I_8_fu_583_p4(9) <= ap_const_lv1_1(0);
    end process;

    res_I_9_fu_601_p3 <= 
        res_I_7_fu_527_p3 when (icmp_ln258_5_fu_561_p2(0) = '1') else 
        res_I_8_fu_583_p4;
    
    res_I_fu_293_p4_proc : process(select_ln216_fu_237_p3)
    begin
        res_I_fu_293_p4 <= select_ln216_fu_237_p3;
        res_I_fu_293_p4(13) <= ap_const_lv1_1(0);
    end process;

    select_ln216_1_fu_244_p3 <= 
        ap_const_lv2_0 when (icmp_ln258_reg_1275(0) = '1') else 
        ap_const_lv2_2;
    select_ln216_fu_237_p3 <= 
        ap_const_lv16_0 when (icmp_ln258_reg_1275(0) = '1') else 
        ap_const_lv16_4000;
        sext_ln263_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln263_reg_1282),4));

    sub_ln263_10_fu_1002_p2 <= std_logic_vector(unsigned(tmp_31_fu_984_p3) - unsigned(zext_ln258_11_fu_992_p1));
    sub_ln263_11_fu_1078_p2 <= std_logic_vector(unsigned(tmp_34_fu_1060_p3) - unsigned(zext_ln258_12_fu_1068_p1));
    sub_ln263_12_fu_1147_p2 <= std_logic_vector(unsigned(tmp_37_fu_1129_p3) - unsigned(zext_ln258_13_fu_1137_p1));
    sub_ln263_13_fu_1211_p2 <= std_logic_vector(unsigned(trunc_ln258_fu_1197_p1) - unsigned(zext_ln258_14_fu_1201_p1));
    sub_ln263_1_fu_353_p2 <= std_logic_vector(unsigned(tmp_8_fu_335_p3) - unsigned(zext_ln258_2_fu_343_p1));
    sub_ln263_2_fu_422_p2 <= std_logic_vector(unsigned(tmp_9_fu_404_p3) - unsigned(zext_ln258_3_fu_412_p1));
    sub_ln263_3_fu_498_p2 <= std_logic_vector(unsigned(tmp_10_fu_480_p3) - unsigned(zext_ln258_4_fu_488_p1));
    sub_ln263_4_fu_567_p2 <= std_logic_vector(unsigned(tmp_13_fu_549_p3) - unsigned(zext_ln258_5_fu_557_p1));
    sub_ln263_5_fu_643_p2 <= std_logic_vector(unsigned(tmp_16_fu_625_p3) - unsigned(zext_ln258_6_fu_633_p1));
    sub_ln263_6_fu_712_p2 <= std_logic_vector(unsigned(tmp_19_fu_694_p3) - unsigned(zext_ln258_7_fu_702_p1));
    sub_ln263_7_fu_788_p2 <= std_logic_vector(unsigned(tmp_22_fu_770_p3) - unsigned(zext_ln258_8_fu_778_p1));
    sub_ln263_8_fu_857_p2 <= std_logic_vector(unsigned(tmp_25_fu_839_p3) - unsigned(zext_ln258_9_fu_847_p1));
    sub_ln263_9_fu_933_p2 <= std_logic_vector(unsigned(tmp_28_fu_915_p3) - unsigned(zext_ln258_10_fu_923_p1));
    sub_ln263_fu_277_p2 <= std_logic_vector(unsigned(tmp_2_fu_259_p3) - unsigned(zext_ln258_1_fu_267_p1));
    tmp_10_fu_480_p3 <= x_l_I_7_fu_448_p3(27 downto 20);
    tmp_11_fu_533_p3 <= res_I_7_fu_527_p3(15 downto 9);
    tmp_12_fu_541_p3 <= (tmp_11_fu_533_p3 & ap_const_lv1_1);
    tmp_13_fu_549_p3 <= x_l_I_9_fu_521_p3(26 downto 18);
    tmp_14_fu_609_p3 <= res_I_9_fu_601_p3(15 downto 8);
    tmp_15_fu_617_p3 <= (tmp_14_fu_609_p3 & ap_const_lv1_1);
    tmp_16_fu_625_p3 <= x_l_I_11_fu_593_p3(25 downto 16);
    tmp_17_fu_678_p3 <= res_I_11_fu_672_p3(15 downto 7);
    tmp_18_fu_686_p3 <= (tmp_17_fu_678_p3 & ap_const_lv1_1);
    tmp_19_fu_694_p3 <= x_l_I_13_fu_666_p3(24 downto 14);
    tmp_1_fu_472_p3 <= (tmp_s_fu_464_p3 & ap_const_lv1_1);
    tmp_20_fu_754_p3 <= res_I_13_fu_746_p3(15 downto 6);
    tmp_21_fu_762_p3 <= (tmp_20_fu_754_p3 & ap_const_lv1_1);
    tmp_22_fu_770_p3 <= x_l_I_15_fu_738_p3(23 downto 12);
    tmp_23_fu_823_p3 <= res_I_15_fu_817_p3(15 downto 5);
    tmp_24_fu_831_p3 <= (tmp_23_fu_823_p3 & ap_const_lv1_1);
    tmp_25_fu_839_p3 <= x_l_I_17_fu_811_p3(22 downto 10);
    tmp_26_fu_899_p3 <= res_I_17_fu_891_p3(15 downto 4);
    tmp_27_fu_907_p3 <= (tmp_26_fu_899_p3 & ap_const_lv1_1);
    tmp_28_fu_915_p3 <= x_l_I_19_fu_883_p3(21 downto 8);
    tmp_29_fu_968_p3 <= res_I_19_fu_962_p3(15 downto 3);
    tmp_2_fu_259_p3 <= x_l_I_1_fu_230_p3(30 downto 26);
    tmp_30_fu_976_p3 <= (tmp_29_fu_968_p3 & ap_const_lv1_1);
    tmp_31_fu_984_p3 <= x_l_I_21_fu_956_p3(20 downto 6);
    tmp_32_fu_1044_p3 <= res_I_21_fu_1036_p3(15 downto 2);
    tmp_33_fu_1052_p3 <= (tmp_32_fu_1044_p3 & ap_const_lv1_1);
    tmp_34_fu_1060_p3 <= x_l_I_23_fu_1028_p3(19 downto 4);
    tmp_35_fu_1113_p3 <= res_I_23_fu_1107_p3(15 downto 1);
    tmp_36_fu_1121_p3 <= (tmp_35_fu_1113_p3 & ap_const_lv1_1);
    tmp_37_fu_1129_p3 <= x_l_I_25_fu_1101_p3(18 downto 2);
    tmp_38_fu_1189_p3 <= (res_I_25_fu_1181_p3 & ap_const_lv1_1);
    tmp_3_fu_251_p3 <= (select_ln216_1_fu_244_p3 & ap_const_lv1_1);
    tmp_4_fu_327_p3 <= (tmp_5_fu_319_p3 & ap_const_lv1_1);
    tmp_5_fu_319_p3 <= res_I_1_fu_311_p3(15 downto 12);
    tmp_6_fu_388_p3 <= res_I_3_fu_382_p3(15 downto 11);
    tmp_7_fu_396_p3 <= (tmp_6_fu_388_p3 & ap_const_lv1_1);
    tmp_8_fu_335_p3 <= x_l_I_3_fu_303_p3(29 downto 24);
    tmp_9_fu_404_p3 <= x_l_I_5_fu_376_p3(28 downto 22);
    tmp_fu_188_p4 <= x_int_reg(29 downto 28);
    tmp_s_fu_464_p3 <= res_I_5_fu_456_p3(15 downto 10);
    trunc_ln258_fu_1197_p1 <= x_l_I_27_fu_1173_p3(18 - 1 downto 0);
    x_l_I_10_fu_573_p4 <= (x_l_I_9_fu_521_p3(33 downto 27) & sub_ln263_4_fu_567_p2 & x_l_I_9_fu_521_p3(17 downto 0));
    x_l_I_11_fu_593_p3 <= 
        x_l_I_9_fu_521_p3 when (icmp_ln258_5_fu_561_p2(0) = '1') else 
        x_l_I_10_fu_573_p4;
    x_l_I_12_fu_649_p4 <= (x_l_I_11_reg_1333(33 downto 26) & sub_ln263_5_reg_1351 & x_l_I_11_reg_1333(15 downto 0));
    x_l_I_13_fu_666_p3 <= 
        x_l_I_11_reg_1333 when (icmp_ln258_6_reg_1345(0) = '1') else 
        x_l_I_12_fu_649_p4;
    x_l_I_14_fu_718_p4 <= (x_l_I_13_fu_666_p3(33 downto 25) & sub_ln263_6_fu_712_p2 & x_l_I_13_fu_666_p3(13 downto 0));
    x_l_I_15_fu_738_p3 <= 
        x_l_I_13_fu_666_p3 when (icmp_ln258_7_fu_706_p2(0) = '1') else 
        x_l_I_14_fu_718_p4;
    x_l_I_16_fu_794_p4 <= (x_l_I_15_reg_1356(33 downto 24) & sub_ln263_7_reg_1374 & x_l_I_15_reg_1356(11 downto 0));
    x_l_I_17_fu_811_p3 <= 
        x_l_I_15_reg_1356 when (icmp_ln258_8_reg_1368(0) = '1') else 
        x_l_I_16_fu_794_p4;
    x_l_I_18_fu_863_p4 <= (x_l_I_17_fu_811_p3(33 downto 23) & sub_ln263_8_fu_857_p2 & x_l_I_17_fu_811_p3(9 downto 0));
    x_l_I_19_fu_883_p3 <= 
        x_l_I_17_fu_811_p3 when (icmp_ln258_9_fu_851_p2(0) = '1') else 
        x_l_I_18_fu_863_p4;
    x_l_I_1_fu_230_p3 <= 
        zext_ln212_fu_214_p1 when (icmp_ln258_reg_1275(0) = '1') else 
        x_l_I_fu_220_p4;
    x_l_I_20_fu_939_p4 <= (x_l_I_19_reg_1379(33 downto 22) & sub_ln263_9_reg_1397 & x_l_I_19_reg_1379(7 downto 0));
    x_l_I_21_fu_956_p3 <= 
        x_l_I_19_reg_1379 when (icmp_ln258_10_reg_1391(0) = '1') else 
        x_l_I_20_fu_939_p4;
    x_l_I_22_fu_1008_p4 <= (x_l_I_21_fu_956_p3(33 downto 21) & sub_ln263_10_fu_1002_p2 & x_l_I_21_fu_956_p3(5 downto 0));
    x_l_I_23_fu_1028_p3 <= 
        x_l_I_21_fu_956_p3 when (icmp_ln258_11_fu_996_p2(0) = '1') else 
        x_l_I_22_fu_1008_p4;
    x_l_I_24_fu_1084_p4 <= (x_l_I_23_reg_1402(33 downto 20) & sub_ln263_11_reg_1420 & x_l_I_23_reg_1402(3 downto 0));
    x_l_I_25_fu_1101_p3 <= 
        x_l_I_23_reg_1402 when (icmp_ln258_12_reg_1414(0) = '1') else 
        x_l_I_24_fu_1084_p4;
    x_l_I_26_fu_1153_p4 <= (x_l_I_25_fu_1101_p3(33 downto 19) & sub_ln263_12_fu_1147_p2 & x_l_I_25_fu_1101_p3(1 downto 0));
    x_l_I_27_fu_1173_p3 <= 
        x_l_I_25_fu_1101_p3 when (icmp_ln258_13_fu_1141_p2(0) = '1') else 
        x_l_I_26_fu_1153_p4;
    x_l_I_28_fu_1217_p4 <= (x_l_I_27_reg_1425(33 downto 18) & sub_ln263_13_reg_1443);
    x_l_I_29_fu_1234_p3 <= 
        x_l_I_27_reg_1425 when (icmp_ln258_14_reg_1437(0) = '1') else 
        x_l_I_28_fu_1217_p4;
    x_l_I_2_fu_283_p4 <= (x_l_I_1_fu_230_p3(33 downto 31) & sub_ln263_fu_277_p2 & x_l_I_1_fu_230_p3(25 downto 0));
    x_l_I_3_fu_303_p3 <= 
        x_l_I_1_fu_230_p3 when (icmp_ln258_1_fu_271_p2(0) = '1') else 
        x_l_I_2_fu_283_p4;
    x_l_I_4_fu_359_p4 <= (x_l_I_3_reg_1287(33 downto 30) & sub_ln263_1_reg_1305 & x_l_I_3_reg_1287(23 downto 0));
    x_l_I_5_fu_376_p3 <= 
        x_l_I_3_reg_1287 when (icmp_ln258_2_reg_1299(0) = '1') else 
        x_l_I_4_fu_359_p4;
    x_l_I_6_fu_428_p4 <= (x_l_I_5_fu_376_p3(33 downto 29) & sub_ln263_2_fu_422_p2 & x_l_I_5_fu_376_p3(21 downto 0));
    x_l_I_7_fu_448_p3 <= 
        x_l_I_5_fu_376_p3 when (icmp_ln258_3_fu_416_p2(0) = '1') else 
        x_l_I_6_fu_428_p4;
    x_l_I_8_fu_504_p4 <= (x_l_I_7_reg_1310(33 downto 28) & sub_ln263_3_reg_1328 & x_l_I_7_reg_1310(19 downto 0));
    x_l_I_9_fu_521_p3 <= 
        x_l_I_7_reg_1310 when (icmp_ln258_4_reg_1322(0) = '1') else 
        x_l_I_8_fu_504_p4;
    x_l_I_fu_220_p4 <= (zext_ln212_fu_214_p1(33 downto 32) & sext_ln263_fu_217_p1 & zext_ln212_fu_214_p1(27 downto 0));
    zext_ln212_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_read_reg_1270),34));
    zext_ln258_10_fu_923_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_27_fu_907_p3),14));
    zext_ln258_11_fu_992_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_fu_976_p3),15));
    zext_ln258_12_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_1052_p3),16));
    zext_ln258_13_fu_1137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_1121_p3),17));
    zext_ln258_14_fu_1201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_1189_p3),18));
    zext_ln258_1_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_251_p3),5));
    zext_ln258_2_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_327_p3),6));
    zext_ln258_3_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_396_p3),7));
    zext_ln258_4_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_472_p3),8));
    zext_ln258_5_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_541_p3),9));
    zext_ln258_6_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_617_p3),10));
    zext_ln258_7_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_686_p3),11));
    zext_ln258_8_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_762_p3),12));
    zext_ln258_9_fu_847_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_831_p3),13));
    zext_ln258_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_188_p4),3));
    zext_ln295_fu_1246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_I_27_fu_1240_p3),34));
end behav;
