// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module euc_dist_sqrt_fixed_31_31_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [29:0] x;
output  [15:0] ap_return;

reg   [29:0] x_read_reg_1270;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln258_fu_202_p2;
reg   [0:0] icmp_ln258_reg_1275;
wire   [2:0] add_ln263_fu_208_p2;
reg   [2:0] add_ln263_reg_1282;
wire   [33:0] x_l_I_3_fu_303_p3;
reg   [33:0] x_l_I_3_reg_1287;
wire   [15:0] res_I_1_fu_311_p3;
reg   [15:0] res_I_1_reg_1293;
wire   [0:0] icmp_ln258_2_fu_347_p2;
reg   [0:0] icmp_ln258_2_reg_1299;
wire   [5:0] sub_ln263_1_fu_353_p2;
reg   [5:0] sub_ln263_1_reg_1305;
wire   [33:0] x_l_I_7_fu_448_p3;
reg   [33:0] x_l_I_7_reg_1310;
wire   [15:0] res_I_5_fu_456_p3;
reg   [15:0] res_I_5_reg_1316;
wire   [0:0] icmp_ln258_4_fu_492_p2;
reg   [0:0] icmp_ln258_4_reg_1322;
wire   [7:0] sub_ln263_3_fu_498_p2;
reg   [7:0] sub_ln263_3_reg_1328;
wire   [33:0] x_l_I_11_fu_593_p3;
reg   [33:0] x_l_I_11_reg_1333;
wire   [15:0] res_I_9_fu_601_p3;
reg   [15:0] res_I_9_reg_1339;
wire   [0:0] icmp_ln258_6_fu_637_p2;
reg   [0:0] icmp_ln258_6_reg_1345;
wire   [9:0] sub_ln263_5_fu_643_p2;
reg   [9:0] sub_ln263_5_reg_1351;
wire   [33:0] x_l_I_15_fu_738_p3;
reg   [33:0] x_l_I_15_reg_1356;
wire   [15:0] res_I_13_fu_746_p3;
reg   [15:0] res_I_13_reg_1362;
wire   [0:0] icmp_ln258_8_fu_782_p2;
reg   [0:0] icmp_ln258_8_reg_1368;
wire   [11:0] sub_ln263_7_fu_788_p2;
reg   [11:0] sub_ln263_7_reg_1374;
wire   [33:0] x_l_I_19_fu_883_p3;
reg   [33:0] x_l_I_19_reg_1379;
wire   [15:0] res_I_17_fu_891_p3;
reg   [15:0] res_I_17_reg_1385;
wire   [0:0] icmp_ln258_10_fu_927_p2;
reg   [0:0] icmp_ln258_10_reg_1391;
wire   [13:0] sub_ln263_9_fu_933_p2;
reg   [13:0] sub_ln263_9_reg_1397;
wire   [33:0] x_l_I_23_fu_1028_p3;
reg   [33:0] x_l_I_23_reg_1402;
wire   [15:0] res_I_21_fu_1036_p3;
reg   [15:0] res_I_21_reg_1408;
wire   [0:0] icmp_ln258_12_fu_1072_p2;
reg   [0:0] icmp_ln258_12_reg_1414;
wire   [15:0] sub_ln263_11_fu_1078_p2;
reg   [15:0] sub_ln263_11_reg_1420;
wire   [33:0] x_l_I_27_fu_1173_p3;
reg   [33:0] x_l_I_27_reg_1425;
wire   [15:0] res_I_25_fu_1181_p3;
reg   [15:0] res_I_25_reg_1431;
wire   [0:0] icmp_ln258_14_fu_1205_p2;
reg   [0:0] icmp_ln258_14_reg_1437;
wire   [17:0] sub_ln263_13_fu_1211_p2;
reg   [17:0] sub_ln263_13_reg_1443;
wire    ap_block_pp0_stage0;
wire   [1:0] tmp_fu_188_p4;
wire   [2:0] zext_ln258_fu_198_p1;
wire   [33:0] zext_ln212_fu_214_p1;
wire  signed [3:0] sext_ln263_fu_217_p1;
wire   [33:0] x_l_I_fu_220_p4;
wire   [1:0] select_ln216_1_fu_244_p3;
wire   [33:0] x_l_I_1_fu_230_p3;
wire   [2:0] tmp_3_fu_251_p3;
wire   [4:0] tmp_2_fu_259_p3;
wire   [4:0] zext_ln258_1_fu_267_p1;
wire   [4:0] sub_ln263_fu_277_p2;
wire   [15:0] select_ln216_fu_237_p3;
wire   [0:0] icmp_ln258_1_fu_271_p2;
wire   [33:0] x_l_I_2_fu_283_p4;
wire   [15:0] res_I_fu_293_p4;
wire   [3:0] tmp_5_fu_319_p3;
wire   [4:0] tmp_4_fu_327_p3;
wire   [5:0] tmp_8_fu_335_p3;
wire   [5:0] zext_ln258_2_fu_343_p1;
wire   [33:0] x_l_I_4_fu_359_p4;
wire   [15:0] res_I_2_fu_367_p4;
wire   [15:0] res_I_3_fu_382_p3;
wire   [4:0] tmp_6_fu_388_p3;
wire   [33:0] x_l_I_5_fu_376_p3;
wire   [5:0] tmp_7_fu_396_p3;
wire   [6:0] tmp_9_fu_404_p3;
wire   [6:0] zext_ln258_3_fu_412_p1;
wire   [6:0] sub_ln263_2_fu_422_p2;
wire   [0:0] icmp_ln258_3_fu_416_p2;
wire   [33:0] x_l_I_6_fu_428_p4;
wire   [15:0] res_I_4_fu_438_p4;
wire   [5:0] tmp_s_fu_464_p3;
wire   [6:0] tmp_1_fu_472_p3;
wire   [7:0] tmp_10_fu_480_p3;
wire   [7:0] zext_ln258_4_fu_488_p1;
wire   [33:0] x_l_I_8_fu_504_p4;
wire   [15:0] res_I_6_fu_512_p4;
wire   [15:0] res_I_7_fu_527_p3;
wire   [6:0] tmp_11_fu_533_p3;
wire   [33:0] x_l_I_9_fu_521_p3;
wire   [7:0] tmp_12_fu_541_p3;
wire   [8:0] tmp_13_fu_549_p3;
wire   [8:0] zext_ln258_5_fu_557_p1;
wire   [8:0] sub_ln263_4_fu_567_p2;
wire   [0:0] icmp_ln258_5_fu_561_p2;
wire   [33:0] x_l_I_10_fu_573_p4;
wire   [15:0] res_I_8_fu_583_p4;
wire   [7:0] tmp_14_fu_609_p3;
wire   [8:0] tmp_15_fu_617_p3;
wire   [9:0] tmp_16_fu_625_p3;
wire   [9:0] zext_ln258_6_fu_633_p1;
wire   [33:0] x_l_I_12_fu_649_p4;
wire   [15:0] res_I_10_fu_657_p4;
wire   [15:0] res_I_11_fu_672_p3;
wire   [8:0] tmp_17_fu_678_p3;
wire   [33:0] x_l_I_13_fu_666_p3;
wire   [9:0] tmp_18_fu_686_p3;
wire   [10:0] tmp_19_fu_694_p3;
wire   [10:0] zext_ln258_7_fu_702_p1;
wire   [10:0] sub_ln263_6_fu_712_p2;
wire   [0:0] icmp_ln258_7_fu_706_p2;
wire   [33:0] x_l_I_14_fu_718_p4;
wire   [15:0] res_I_12_fu_728_p4;
wire   [9:0] tmp_20_fu_754_p3;
wire   [10:0] tmp_21_fu_762_p3;
wire   [11:0] tmp_22_fu_770_p3;
wire   [11:0] zext_ln258_8_fu_778_p1;
wire   [33:0] x_l_I_16_fu_794_p4;
wire   [15:0] res_I_14_fu_802_p4;
wire   [15:0] res_I_15_fu_817_p3;
wire   [10:0] tmp_23_fu_823_p3;
wire   [33:0] x_l_I_17_fu_811_p3;
wire   [11:0] tmp_24_fu_831_p3;
wire   [12:0] tmp_25_fu_839_p3;
wire   [12:0] zext_ln258_9_fu_847_p1;
wire   [12:0] sub_ln263_8_fu_857_p2;
wire   [0:0] icmp_ln258_9_fu_851_p2;
wire   [33:0] x_l_I_18_fu_863_p4;
wire   [15:0] res_I_16_fu_873_p4;
wire   [11:0] tmp_26_fu_899_p3;
wire   [12:0] tmp_27_fu_907_p3;
wire   [13:0] tmp_28_fu_915_p3;
wire   [13:0] zext_ln258_10_fu_923_p1;
wire   [33:0] x_l_I_20_fu_939_p4;
wire   [15:0] res_I_18_fu_947_p4;
wire   [15:0] res_I_19_fu_962_p3;
wire   [12:0] tmp_29_fu_968_p3;
wire   [33:0] x_l_I_21_fu_956_p3;
wire   [13:0] tmp_30_fu_976_p3;
wire   [14:0] tmp_31_fu_984_p3;
wire   [14:0] zext_ln258_11_fu_992_p1;
wire   [14:0] sub_ln263_10_fu_1002_p2;
wire   [0:0] icmp_ln258_11_fu_996_p2;
wire   [33:0] x_l_I_22_fu_1008_p4;
wire   [15:0] res_I_20_fu_1018_p4;
wire   [13:0] tmp_32_fu_1044_p3;
wire   [14:0] tmp_33_fu_1052_p3;
wire   [15:0] tmp_34_fu_1060_p3;
wire   [15:0] zext_ln258_12_fu_1068_p1;
wire   [33:0] x_l_I_24_fu_1084_p4;
wire   [15:0] res_I_22_fu_1092_p4;
wire   [15:0] res_I_23_fu_1107_p3;
wire   [14:0] tmp_35_fu_1113_p3;
wire   [33:0] x_l_I_25_fu_1101_p3;
wire   [15:0] tmp_36_fu_1121_p3;
wire   [16:0] tmp_37_fu_1129_p3;
wire   [16:0] zext_ln258_13_fu_1137_p1;
wire   [16:0] sub_ln263_12_fu_1147_p2;
wire   [0:0] icmp_ln258_13_fu_1141_p2;
wire   [33:0] x_l_I_26_fu_1153_p4;
wire   [15:0] res_I_24_fu_1163_p4;
wire   [16:0] tmp_38_fu_1189_p3;
wire   [17:0] trunc_ln258_fu_1197_p1;
wire   [17:0] zext_ln258_14_fu_1201_p1;
wire   [33:0] x_l_I_28_fu_1217_p4;
wire   [15:0] res_I_26_fu_1225_p4;
wire   [15:0] res_I_27_fu_1240_p3;
wire   [33:0] x_l_I_29_fu_1234_p3;
wire   [33:0] zext_ln295_fu_1246_p1;
wire   [0:0] icmp_ln295_fu_1250_p2;
wire   [15:0] add_ln340_fu_1256_p2;
reg   [29:0] x_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln263_reg_1282 <= add_ln263_fu_208_p2;
        icmp_ln258_10_reg_1391 <= icmp_ln258_10_fu_927_p2;
        icmp_ln258_12_reg_1414 <= icmp_ln258_12_fu_1072_p2;
        icmp_ln258_14_reg_1437 <= icmp_ln258_14_fu_1205_p2;
        icmp_ln258_2_reg_1299 <= icmp_ln258_2_fu_347_p2;
        icmp_ln258_4_reg_1322 <= icmp_ln258_4_fu_492_p2;
        icmp_ln258_6_reg_1345 <= icmp_ln258_6_fu_637_p2;
        icmp_ln258_8_reg_1368 <= icmp_ln258_8_fu_782_p2;
        icmp_ln258_reg_1275 <= icmp_ln258_fu_202_p2;
        res_I_13_reg_1362 <= res_I_13_fu_746_p3;
        res_I_17_reg_1385 <= res_I_17_fu_891_p3;
        res_I_1_reg_1293 <= res_I_1_fu_311_p3;
        res_I_21_reg_1408 <= res_I_21_fu_1036_p3;
        res_I_25_reg_1431 <= res_I_25_fu_1181_p3;
        res_I_5_reg_1316 <= res_I_5_fu_456_p3;
        res_I_9_reg_1339 <= res_I_9_fu_601_p3;
        sub_ln263_11_reg_1420 <= sub_ln263_11_fu_1078_p2;
        sub_ln263_13_reg_1443 <= sub_ln263_13_fu_1211_p2;
        sub_ln263_1_reg_1305 <= sub_ln263_1_fu_353_p2;
        sub_ln263_3_reg_1328 <= sub_ln263_3_fu_498_p2;
        sub_ln263_5_reg_1351 <= sub_ln263_5_fu_643_p2;
        sub_ln263_7_reg_1374 <= sub_ln263_7_fu_788_p2;
        sub_ln263_9_reg_1397 <= sub_ln263_9_fu_933_p2;
        x_l_I_11_reg_1333 <= x_l_I_11_fu_593_p3;
        x_l_I_15_reg_1356 <= x_l_I_15_fu_738_p3;
        x_l_I_19_reg_1379 <= x_l_I_19_fu_883_p3;
        x_l_I_23_reg_1402 <= x_l_I_23_fu_1028_p3;
        x_l_I_27_reg_1425 <= x_l_I_27_fu_1173_p3;
        x_l_I_3_reg_1287 <= x_l_I_3_fu_303_p3;
        x_l_I_7_reg_1310 <= x_l_I_7_fu_448_p3;
        x_read_reg_1270 <= x_int_reg;
    end
end

assign add_ln263_fu_208_p2 = ($signed(zext_ln258_fu_198_p1) + $signed(3'd7));

assign add_ln340_fu_1256_p2 = (res_I_27_fu_1240_p3 + 16'd1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = ((icmp_ln295_fu_1250_p2[0:0] == 1'b1) ? add_ln340_fu_1256_p2 : res_I_27_fu_1240_p3);

assign icmp_ln258_10_fu_927_p2 = ((tmp_28_fu_915_p3 < zext_ln258_10_fu_923_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_11_fu_996_p2 = ((tmp_31_fu_984_p3 < zext_ln258_11_fu_992_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_12_fu_1072_p2 = ((tmp_34_fu_1060_p3 < zext_ln258_12_fu_1068_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_13_fu_1141_p2 = ((tmp_37_fu_1129_p3 < zext_ln258_13_fu_1137_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_14_fu_1205_p2 = ((trunc_ln258_fu_1197_p1 < zext_ln258_14_fu_1201_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_1_fu_271_p2 = ((tmp_2_fu_259_p3 < zext_ln258_1_fu_267_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_2_fu_347_p2 = ((tmp_8_fu_335_p3 < zext_ln258_2_fu_343_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_3_fu_416_p2 = ((tmp_9_fu_404_p3 < zext_ln258_3_fu_412_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_4_fu_492_p2 = ((tmp_10_fu_480_p3 < zext_ln258_4_fu_488_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_5_fu_561_p2 = ((tmp_13_fu_549_p3 < zext_ln258_5_fu_557_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_6_fu_637_p2 = ((tmp_16_fu_625_p3 < zext_ln258_6_fu_633_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_7_fu_706_p2 = ((tmp_19_fu_694_p3 < zext_ln258_7_fu_702_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_8_fu_782_p2 = ((tmp_22_fu_770_p3 < zext_ln258_8_fu_778_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_9_fu_851_p2 = ((tmp_25_fu_839_p3 < zext_ln258_9_fu_847_p1) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_202_p2 = ((tmp_fu_188_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln295_fu_1250_p2 = ((x_l_I_29_fu_1234_p3 > zext_ln295_fu_1246_p1) ? 1'b1 : 1'b0);

assign res_I_10_fu_657_p4 = {res_I_9_reg_1339[16 - 1:9], |(1'd1), res_I_9_reg_1339[7:0]};

assign res_I_11_fu_672_p3 = ((icmp_ln258_6_reg_1345[0:0] == 1'b1) ? res_I_9_reg_1339 : res_I_10_fu_657_p4);

assign res_I_12_fu_728_p4 = {res_I_11_fu_672_p3[16 - 1:8], |(1'd1), res_I_11_fu_672_p3[6:0]};

assign res_I_13_fu_746_p3 = ((icmp_ln258_7_fu_706_p2[0:0] == 1'b1) ? res_I_11_fu_672_p3 : res_I_12_fu_728_p4);

assign res_I_14_fu_802_p4 = {res_I_13_reg_1362[16 - 1:7], |(1'd1), res_I_13_reg_1362[5:0]};

assign res_I_15_fu_817_p3 = ((icmp_ln258_8_reg_1368[0:0] == 1'b1) ? res_I_13_reg_1362 : res_I_14_fu_802_p4);

assign res_I_16_fu_873_p4 = {res_I_15_fu_817_p3[16 - 1:6], |(1'd1), res_I_15_fu_817_p3[4:0]};

assign res_I_17_fu_891_p3 = ((icmp_ln258_9_fu_851_p2[0:0] == 1'b1) ? res_I_15_fu_817_p3 : res_I_16_fu_873_p4);

assign res_I_18_fu_947_p4 = {res_I_17_reg_1385[16 - 1:5], |(1'd1), res_I_17_reg_1385[3:0]};

assign res_I_19_fu_962_p3 = ((icmp_ln258_10_reg_1391[0:0] == 1'b1) ? res_I_17_reg_1385 : res_I_18_fu_947_p4);

assign res_I_1_fu_311_p3 = ((icmp_ln258_1_fu_271_p2[0:0] == 1'b1) ? select_ln216_fu_237_p3 : res_I_fu_293_p4);

assign res_I_20_fu_1018_p4 = {res_I_19_fu_962_p3[16 - 1:4], |(1'd1), res_I_19_fu_962_p3[2:0]};

assign res_I_21_fu_1036_p3 = ((icmp_ln258_11_fu_996_p2[0:0] == 1'b1) ? res_I_19_fu_962_p3 : res_I_20_fu_1018_p4);

assign res_I_22_fu_1092_p4 = {res_I_21_reg_1408[16 - 1:3], |(1'd1), res_I_21_reg_1408[1:0]};

assign res_I_23_fu_1107_p3 = ((icmp_ln258_12_reg_1414[0:0] == 1'b1) ? res_I_21_reg_1408 : res_I_22_fu_1092_p4);

assign res_I_24_fu_1163_p4 = {res_I_23_fu_1107_p3[16 - 1:2], |(1'd1), res_I_23_fu_1107_p3[0:0]};

assign res_I_25_fu_1181_p3 = ((icmp_ln258_13_fu_1141_p2[0:0] == 1'b1) ? res_I_23_fu_1107_p3 : res_I_24_fu_1163_p4);

assign res_I_26_fu_1225_p4 = {res_I_25_reg_1431[16-1:1], |(1'd1)};

assign res_I_27_fu_1240_p3 = ((icmp_ln258_14_reg_1437[0:0] == 1'b1) ? res_I_25_reg_1431 : res_I_26_fu_1225_p4);

assign res_I_2_fu_367_p4 = {res_I_1_reg_1293[16 - 1:13], |(1'd1), res_I_1_reg_1293[11:0]};

assign res_I_3_fu_382_p3 = ((icmp_ln258_2_reg_1299[0:0] == 1'b1) ? res_I_1_reg_1293 : res_I_2_fu_367_p4);

assign res_I_4_fu_438_p4 = {res_I_3_fu_382_p3[16 - 1:12], |(1'd1), res_I_3_fu_382_p3[10:0]};

assign res_I_5_fu_456_p3 = ((icmp_ln258_3_fu_416_p2[0:0] == 1'b1) ? res_I_3_fu_382_p3 : res_I_4_fu_438_p4);

assign res_I_6_fu_512_p4 = {res_I_5_reg_1316[16 - 1:11], |(1'd1), res_I_5_reg_1316[9:0]};

assign res_I_7_fu_527_p3 = ((icmp_ln258_4_reg_1322[0:0] == 1'b1) ? res_I_5_reg_1316 : res_I_6_fu_512_p4);

assign res_I_8_fu_583_p4 = {res_I_7_fu_527_p3[16 - 1:10], |(1'd1), res_I_7_fu_527_p3[8:0]};

assign res_I_9_fu_601_p3 = ((icmp_ln258_5_fu_561_p2[0:0] == 1'b1) ? res_I_7_fu_527_p3 : res_I_8_fu_583_p4);

assign res_I_fu_293_p4 = {select_ln216_fu_237_p3[16 - 1:14], |(1'd1), select_ln216_fu_237_p3[12:0]};

assign select_ln216_1_fu_244_p3 = ((icmp_ln258_reg_1275[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign select_ln216_fu_237_p3 = ((icmp_ln258_reg_1275[0:0] == 1'b1) ? 16'd0 : 16'd16384);

assign sext_ln263_fu_217_p1 = $signed(add_ln263_reg_1282);

assign sub_ln263_10_fu_1002_p2 = (tmp_31_fu_984_p3 - zext_ln258_11_fu_992_p1);

assign sub_ln263_11_fu_1078_p2 = (tmp_34_fu_1060_p3 - zext_ln258_12_fu_1068_p1);

assign sub_ln263_12_fu_1147_p2 = (tmp_37_fu_1129_p3 - zext_ln258_13_fu_1137_p1);

assign sub_ln263_13_fu_1211_p2 = (trunc_ln258_fu_1197_p1 - zext_ln258_14_fu_1201_p1);

assign sub_ln263_1_fu_353_p2 = (tmp_8_fu_335_p3 - zext_ln258_2_fu_343_p1);

assign sub_ln263_2_fu_422_p2 = (tmp_9_fu_404_p3 - zext_ln258_3_fu_412_p1);

assign sub_ln263_3_fu_498_p2 = (tmp_10_fu_480_p3 - zext_ln258_4_fu_488_p1);

assign sub_ln263_4_fu_567_p2 = (tmp_13_fu_549_p3 - zext_ln258_5_fu_557_p1);

assign sub_ln263_5_fu_643_p2 = (tmp_16_fu_625_p3 - zext_ln258_6_fu_633_p1);

assign sub_ln263_6_fu_712_p2 = (tmp_19_fu_694_p3 - zext_ln258_7_fu_702_p1);

assign sub_ln263_7_fu_788_p2 = (tmp_22_fu_770_p3 - zext_ln258_8_fu_778_p1);

assign sub_ln263_8_fu_857_p2 = (tmp_25_fu_839_p3 - zext_ln258_9_fu_847_p1);

assign sub_ln263_9_fu_933_p2 = (tmp_28_fu_915_p3 - zext_ln258_10_fu_923_p1);

assign sub_ln263_fu_277_p2 = (tmp_2_fu_259_p3 - zext_ln258_1_fu_267_p1);

assign tmp_10_fu_480_p3 = {{x_l_I_7_fu_448_p3[27:20]}};

assign tmp_11_fu_533_p3 = {{res_I_7_fu_527_p3[15:9]}};

assign tmp_12_fu_541_p3 = {{tmp_11_fu_533_p3}, {1'd1}};

assign tmp_13_fu_549_p3 = {{x_l_I_9_fu_521_p3[26:18]}};

assign tmp_14_fu_609_p3 = {{res_I_9_fu_601_p3[15:8]}};

assign tmp_15_fu_617_p3 = {{tmp_14_fu_609_p3}, {1'd1}};

assign tmp_16_fu_625_p3 = {{x_l_I_11_fu_593_p3[25:16]}};

assign tmp_17_fu_678_p3 = {{res_I_11_fu_672_p3[15:7]}};

assign tmp_18_fu_686_p3 = {{tmp_17_fu_678_p3}, {1'd1}};

assign tmp_19_fu_694_p3 = {{x_l_I_13_fu_666_p3[24:14]}};

assign tmp_1_fu_472_p3 = {{tmp_s_fu_464_p3}, {1'd1}};

assign tmp_20_fu_754_p3 = {{res_I_13_fu_746_p3[15:6]}};

assign tmp_21_fu_762_p3 = {{tmp_20_fu_754_p3}, {1'd1}};

assign tmp_22_fu_770_p3 = {{x_l_I_15_fu_738_p3[23:12]}};

assign tmp_23_fu_823_p3 = {{res_I_15_fu_817_p3[15:5]}};

assign tmp_24_fu_831_p3 = {{tmp_23_fu_823_p3}, {1'd1}};

assign tmp_25_fu_839_p3 = {{x_l_I_17_fu_811_p3[22:10]}};

assign tmp_26_fu_899_p3 = {{res_I_17_fu_891_p3[15:4]}};

assign tmp_27_fu_907_p3 = {{tmp_26_fu_899_p3}, {1'd1}};

assign tmp_28_fu_915_p3 = {{x_l_I_19_fu_883_p3[21:8]}};

assign tmp_29_fu_968_p3 = {{res_I_19_fu_962_p3[15:3]}};

assign tmp_2_fu_259_p3 = {{x_l_I_1_fu_230_p3[30:26]}};

assign tmp_30_fu_976_p3 = {{tmp_29_fu_968_p3}, {1'd1}};

assign tmp_31_fu_984_p3 = {{x_l_I_21_fu_956_p3[20:6]}};

assign tmp_32_fu_1044_p3 = {{res_I_21_fu_1036_p3[15:2]}};

assign tmp_33_fu_1052_p3 = {{tmp_32_fu_1044_p3}, {1'd1}};

assign tmp_34_fu_1060_p3 = {{x_l_I_23_fu_1028_p3[19:4]}};

assign tmp_35_fu_1113_p3 = {{res_I_23_fu_1107_p3[15:1]}};

assign tmp_36_fu_1121_p3 = {{tmp_35_fu_1113_p3}, {1'd1}};

assign tmp_37_fu_1129_p3 = {{x_l_I_25_fu_1101_p3[18:2]}};

assign tmp_38_fu_1189_p3 = {{res_I_25_fu_1181_p3}, {1'd1}};

assign tmp_3_fu_251_p3 = {{select_ln216_1_fu_244_p3}, {1'd1}};

assign tmp_4_fu_327_p3 = {{tmp_5_fu_319_p3}, {1'd1}};

assign tmp_5_fu_319_p3 = {{res_I_1_fu_311_p3[15:12]}};

assign tmp_6_fu_388_p3 = {{res_I_3_fu_382_p3[15:11]}};

assign tmp_7_fu_396_p3 = {{tmp_6_fu_388_p3}, {1'd1}};

assign tmp_8_fu_335_p3 = {{x_l_I_3_fu_303_p3[29:24]}};

assign tmp_9_fu_404_p3 = {{x_l_I_5_fu_376_p3[28:22]}};

assign tmp_fu_188_p4 = {{x_int_reg[29:28]}};

assign tmp_s_fu_464_p3 = {{res_I_5_fu_456_p3[15:10]}};

assign trunc_ln258_fu_1197_p1 = x_l_I_27_fu_1173_p3[17:0];

assign x_l_I_10_fu_573_p4 = {{x_l_I_9_fu_521_p3[33:27]}, {sub_ln263_4_fu_567_p2}, {x_l_I_9_fu_521_p3[17:0]}};

assign x_l_I_11_fu_593_p3 = ((icmp_ln258_5_fu_561_p2[0:0] == 1'b1) ? x_l_I_9_fu_521_p3 : x_l_I_10_fu_573_p4);

assign x_l_I_12_fu_649_p4 = {{x_l_I_11_reg_1333[33:26]}, {sub_ln263_5_reg_1351}, {x_l_I_11_reg_1333[15:0]}};

assign x_l_I_13_fu_666_p3 = ((icmp_ln258_6_reg_1345[0:0] == 1'b1) ? x_l_I_11_reg_1333 : x_l_I_12_fu_649_p4);

assign x_l_I_14_fu_718_p4 = {{x_l_I_13_fu_666_p3[33:25]}, {sub_ln263_6_fu_712_p2}, {x_l_I_13_fu_666_p3[13:0]}};

assign x_l_I_15_fu_738_p3 = ((icmp_ln258_7_fu_706_p2[0:0] == 1'b1) ? x_l_I_13_fu_666_p3 : x_l_I_14_fu_718_p4);

assign x_l_I_16_fu_794_p4 = {{x_l_I_15_reg_1356[33:24]}, {sub_ln263_7_reg_1374}, {x_l_I_15_reg_1356[11:0]}};

assign x_l_I_17_fu_811_p3 = ((icmp_ln258_8_reg_1368[0:0] == 1'b1) ? x_l_I_15_reg_1356 : x_l_I_16_fu_794_p4);

assign x_l_I_18_fu_863_p4 = {{x_l_I_17_fu_811_p3[33:23]}, {sub_ln263_8_fu_857_p2}, {x_l_I_17_fu_811_p3[9:0]}};

assign x_l_I_19_fu_883_p3 = ((icmp_ln258_9_fu_851_p2[0:0] == 1'b1) ? x_l_I_17_fu_811_p3 : x_l_I_18_fu_863_p4);

assign x_l_I_1_fu_230_p3 = ((icmp_ln258_reg_1275[0:0] == 1'b1) ? zext_ln212_fu_214_p1 : x_l_I_fu_220_p4);

assign x_l_I_20_fu_939_p4 = {{x_l_I_19_reg_1379[33:22]}, {sub_ln263_9_reg_1397}, {x_l_I_19_reg_1379[7:0]}};

assign x_l_I_21_fu_956_p3 = ((icmp_ln258_10_reg_1391[0:0] == 1'b1) ? x_l_I_19_reg_1379 : x_l_I_20_fu_939_p4);

assign x_l_I_22_fu_1008_p4 = {{x_l_I_21_fu_956_p3[33:21]}, {sub_ln263_10_fu_1002_p2}, {x_l_I_21_fu_956_p3[5:0]}};

assign x_l_I_23_fu_1028_p3 = ((icmp_ln258_11_fu_996_p2[0:0] == 1'b1) ? x_l_I_21_fu_956_p3 : x_l_I_22_fu_1008_p4);

assign x_l_I_24_fu_1084_p4 = {{x_l_I_23_reg_1402[33:20]}, {sub_ln263_11_reg_1420}, {x_l_I_23_reg_1402[3:0]}};

assign x_l_I_25_fu_1101_p3 = ((icmp_ln258_12_reg_1414[0:0] == 1'b1) ? x_l_I_23_reg_1402 : x_l_I_24_fu_1084_p4);

assign x_l_I_26_fu_1153_p4 = {{x_l_I_25_fu_1101_p3[33:19]}, {sub_ln263_12_fu_1147_p2}, {x_l_I_25_fu_1101_p3[1:0]}};

assign x_l_I_27_fu_1173_p3 = ((icmp_ln258_13_fu_1141_p2[0:0] == 1'b1) ? x_l_I_25_fu_1101_p3 : x_l_I_26_fu_1153_p4);

assign x_l_I_28_fu_1217_p4 = {{x_l_I_27_reg_1425[33:18]}, {sub_ln263_13_reg_1443}};

assign x_l_I_29_fu_1234_p3 = ((icmp_ln258_14_reg_1437[0:0] == 1'b1) ? x_l_I_27_reg_1425 : x_l_I_28_fu_1217_p4);

assign x_l_I_2_fu_283_p4 = {{x_l_I_1_fu_230_p3[33:31]}, {sub_ln263_fu_277_p2}, {x_l_I_1_fu_230_p3[25:0]}};

assign x_l_I_3_fu_303_p3 = ((icmp_ln258_1_fu_271_p2[0:0] == 1'b1) ? x_l_I_1_fu_230_p3 : x_l_I_2_fu_283_p4);

assign x_l_I_4_fu_359_p4 = {{x_l_I_3_reg_1287[33:30]}, {sub_ln263_1_reg_1305}, {x_l_I_3_reg_1287[23:0]}};

assign x_l_I_5_fu_376_p3 = ((icmp_ln258_2_reg_1299[0:0] == 1'b1) ? x_l_I_3_reg_1287 : x_l_I_4_fu_359_p4);

assign x_l_I_6_fu_428_p4 = {{x_l_I_5_fu_376_p3[33:29]}, {sub_ln263_2_fu_422_p2}, {x_l_I_5_fu_376_p3[21:0]}};

assign x_l_I_7_fu_448_p3 = ((icmp_ln258_3_fu_416_p2[0:0] == 1'b1) ? x_l_I_5_fu_376_p3 : x_l_I_6_fu_428_p4);

assign x_l_I_8_fu_504_p4 = {{x_l_I_7_reg_1310[33:28]}, {sub_ln263_3_reg_1328}, {x_l_I_7_reg_1310[19:0]}};

assign x_l_I_9_fu_521_p3 = ((icmp_ln258_4_reg_1322[0:0] == 1'b1) ? x_l_I_7_reg_1310 : x_l_I_8_fu_504_p4);

assign x_l_I_fu_220_p4 = {{zext_ln212_fu_214_p1[33:32]}, {sext_ln263_fu_217_p1}, {zext_ln212_fu_214_p1[27:0]}};

assign zext_ln212_fu_214_p1 = x_read_reg_1270;

assign zext_ln258_10_fu_923_p1 = tmp_27_fu_907_p3;

assign zext_ln258_11_fu_992_p1 = tmp_30_fu_976_p3;

assign zext_ln258_12_fu_1068_p1 = tmp_33_fu_1052_p3;

assign zext_ln258_13_fu_1137_p1 = tmp_36_fu_1121_p3;

assign zext_ln258_14_fu_1201_p1 = tmp_38_fu_1189_p3;

assign zext_ln258_1_fu_267_p1 = tmp_3_fu_251_p3;

assign zext_ln258_2_fu_343_p1 = tmp_4_fu_327_p3;

assign zext_ln258_3_fu_412_p1 = tmp_7_fu_396_p3;

assign zext_ln258_4_fu_488_p1 = tmp_1_fu_472_p3;

assign zext_ln258_5_fu_557_p1 = tmp_12_fu_541_p3;

assign zext_ln258_6_fu_633_p1 = tmp_15_fu_617_p3;

assign zext_ln258_7_fu_702_p1 = tmp_18_fu_686_p3;

assign zext_ln258_8_fu_778_p1 = tmp_21_fu_762_p3;

assign zext_ln258_9_fu_847_p1 = tmp_24_fu_831_p3;

assign zext_ln258_fu_198_p1 = tmp_fu_188_p4;

assign zext_ln295_fu_1246_p1 = res_I_27_fu_1240_p3;

endmodule //euc_dist_sqrt_fixed_31_31_s
